import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { html, jsonLd, safeUrl, safeRoute } from "./content-utils.mjs";
import { sitemapEntries, validateUpdateDates } from "./content-dates.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const data = JSON.parse(fs.readFileSync(path.join(root, "data/projects.json"), "utf8"));
const manifest = JSON.parse(fs.readFileSync(path.join(root, "content/manifest.json"), "utf8"));
const hubs = JSON.parse(fs.readFileSync(path.join(root, "content/hubs.json"), "utf8"));
const linkGroups = JSON.parse(fs.readFileSync(path.join(root, "content/link-groups.json"), "utf8"));
const siteRoutes = JSON.parse(fs.readFileSync(path.join(root, "content/site-routes.json"), "utf8"));
const sourceReview = JSON.parse(fs.readFileSync(path.join(root, "content/source-review.json"), "utf8"));
const assetVersion = fs.readFileSync(path.join(root,"script.js"),"utf8").match(/const DATA_VERSION = "([0-9]{8}-[0-9]+)";/)?.[1];
if (!assetVersion) throw Error("Missing shared asset cache version");
const imageDimensions = JSON.parse(fs.readFileSync(path.join(root, "content/image-dimensions.json"), "utf8"));
const copy = {
  ...JSON.parse(fs.readFileSync(path.join(root, "content/game-app-copy.json"), "utf8")),
  ...JSON.parse(fs.readFileSync(path.join(root, "content/book-music-copy.json"), "utf8")),
};
const generatedMarker = "<!-- Generated by scripts/build-content.mjs. Edit content records, then rebuild. -->";
const base = "https://samfa12.com";
const organizationNode = () => ({"@type":"Organization","@id":`${base}/#organization`,name:"Samfa12",url:`${base}/`});
const websiteNode = () => ({"@type":"WebSite","@id":`${base}/#website`,url:`${base}/`,name:"Samfa12",publisher:{"@id":`${base}/#organization`}});
const pageNode = (route,name,type="WebPage") => ({"@type":type,"@id":`${base}${route}#webpage`,url:`${base}${route}`,name,isPartOf:{"@id":`${base}/#website`}});
const errors = [];
const outputs = new Map();
const productsById = new Map(data.map((item) => [item.id, item]));
const plansById = new Map(manifest.products.map((item) => [item.id, item]));

function xml(value) { return html(value); }
function write(relative, text) {
  if (path.isAbsolute(relative) || relative.includes("..") || relative.includes("\\")) throw Error(`Unsafe output: ${relative}`);
  if (outputs.has(relative)) throw Error(`Duplicate output: ${relative}`);
  outputs.set(relative, text.replace(/\r\n/g, "\n"));
}
function link(label, url, className = "project-link") {
  const href = safeUrl(url);
  const external = /^https?:/.test(href);
  return `<a class="${html(className)}" href="${html(href)}"${external ? ' target="_blank" rel="noopener noreferrer"' : ""}>${html(label)} <span class="link-arrow" aria-hidden="true">-&gt;</span></a>`;
}
function card(project, index, featured = false) {
  const detail = project.detailUrl ? safeUrl(project.detailUrl) : "";
  const first = project.links?.[0];
  const actions = (featured ? project.links?.slice(0, 1) : project.links) || [];
  const size = featured ? (project.homepageSize || (index === 0 ? "hero" : "standard")) : "standard";
  const accent = project.accent || (project.category === "Books" ? "spark" : project.category === "Music" ? "pink" : project.category === "Apps & Tools" || project.category === "Assets" ? "green" : index % 2 ? "violet" : "cyan");
  const [imageWidth, imageHeight] = imageDimensions[project.thumbnail] || [640, 540];
  const image = project.thumbnail ? `<div class="project-media${project.category === "Books" ? " project-media-book" : ""}"><img class="project-image${project.imageFit === "cover" ? " project-image-cover-fill" : ""}" src="/${html(project.thumbnail)}" alt="${html(project.thumbnailAlt || `${project.title} artwork`)}" loading="lazy" width="${imageWidth}" height="${imageHeight}"></div>` : "";
  const title = detail ? `<a class="project-card-title-link" href="${html(detail)}" data-project-title="${html(project.title)}" data-project-category="${html(project.category)}" data-link-label="View ${html(project.category === "Books" ? "book" : project.category === "Music" ? "album" : project.category === "Games" ? "game" : "project")} page">${html(project.title)}</a>` : html(project.title);
  const buttons = actions.map((item, i) => `<a class="project-link${i === 0 ? " project-link-primary" : ""}" href="${html(safeUrl(item.url))}" data-project-title="${html(project.title)}" data-project-category="${html(project.category)}" data-link-label="${html(item.label)}"${item.fullscreen ? ` data-fullscreen-game="${html(item.url)}"` : ""}${/^https?:/.test(item.url) ? ' target="_blank" rel="noopener noreferrer"' : ""}>${html(item.label)} <span class="link-arrow" aria-hidden="true">-&gt;</span></a>`).join("\n");
  const statusClass = /coming soon/i.test(project.status) ? "status-coming-soon" : /development/i.test(project.status) ? "status-development" : /prototype|alpha/i.test(project.status) ? "status-prototype" : /experimental/i.test(project.status) ? "status-experimental" : /published/i.test(project.status) ? "status-published" : "status-available";
  return `<article class="project-card project-card-${featured ? "featured" : "catalogue"} card-size-${html(size)}" data-accent="${html(accent)}" data-project-id="${html(project.id)}">${image}<p class="project-label">${html(project.type || "Project")}${featured ? ` // ${html(project.category)}` : ""}</p><h3>${title}</h3><p class="card-description">${html(project.description)}</p><p class="project-meta"><span class="pill ${statusClass}">${html(project.status)}</span></p><div class="project-actions" role="group" aria-label="${html(project.title)} links">${buttons || (detail ? link("About this project", detail) : "")}</div></article>`;
}
function bySort(a, b) { return (Number(a.sortOrder ?? 9999) - Number(b.sortOrder ?? 9999)) || a.title.localeCompare(b.title); }
function selected(page) {
  if (page === "home") return data.filter((p) => p.homepageRank || p.featured).sort((a,b) => (Number(a.homepageRank || 10000) - Number(b.homepageRank || 10000)) || bySort(a,b)).slice(0,6);
  if (page === "Games" || page === "Books" || page === "Music") return data.filter((p) => p.category === page || p.catalogues?.includes(page)).sort(bySort);
  if (page === "apps") return data.filter((p) => ["Apps & Tools", "Assets"].includes(p.category)).sort(bySort);
  if (page === "pocket-audio") return data.filter((p) => ["Apps & Tools", "Assets"].includes(p.category) && `${p.title} ${p.description} ${(p.tags || []).join(" ")}`.toLowerCase().includes("pocket")).sort(bySort);
  if (page === "links") return data.filter((p) => ["Social", "Storefronts"].includes(p.category)).sort(bySort);
  throw Error(`Unknown catalogue page ${page}`);
}
function replaceManaged(relative, start, end, contents) {
  const file = path.join(root, relative);
  const original = fs.readFileSync(file, "utf8");
  const before = original.indexOf(start);
  const after = original.indexOf(end);
  if (before < 0 || after < before || original.indexOf(start, before + start.length) !== -1 || original.indexOf(end, after + end.length) !== -1) throw Error(`Missing or duplicate content markers in ${relative}`);
  write(relative, original.slice(0, before + start.length) + "\n" + contents + "\n" + original.slice(after));
}
function header(active) {
  const nav = [["Home","/"],["Games","/games/"],["Apps","/apps/"],["Stats","/stats/"],["Books","/books/"],["Pocket Audio","/pocket-audio/"],["Music","/music/"],["Links","/links/"],["Join","/join/"]];
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header" data-site-header><div class="container header-inner"><a class="brand" href="/" aria-label="Samfa12 home"><span class="brand-orb" aria-hidden="true"><img class="brand-mark" src="/assets/samfa12-character.jpg" alt="" width="40" height="40"></span><span>Samfa12</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation" data-menu-toggle><span class="menu-toggle-bars" aria-hidden="true"></span><span class="sr-only">Menu</span></button><nav id="primary-navigation" class="site-nav" aria-label="Primary navigation" data-nav-panel><ul class="nav-links">${nav.map(([label,url])=>`<li><a href="${url}"${label === active ? ' aria-current="page"' : ""}>${label}</a></li>`).join("")}</ul><button class="surprise-button" type="button" data-surprise disabled>Surprise me</button></nav></div></header>`;
}
function footer() {
  return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><a class="footer-brand" href="/" aria-label="Samfa12 home"><span class="brand-orb" aria-hidden="true"><img class="brand-mark" src="/assets/samfa12-character.jpg" alt="" width="40" height="40"></span><span>Samfa12</span></a><p class="footer-copy">Games, stories, music, tools, and experiments from the Samfa12 signal lab.</p></div><nav aria-label="Footer navigation"><h2 class="footer-heading">Explore</h2><div class="footer-links"><a href="/games/">Games</a><a href="/apps/">Apps</a><a href="/books/">Books</a><a href="/pocket-audio/">Pocket Audio</a><a href="/music/">Music</a><a href="/links/">Links</a><a href="/updates/">Updates</a><a href="/about/">About</a><a href="/privacy/">Privacy</a></div></nav></div><p class="footer-meta">&copy; <span data-current-year>2026</span> Samfa12</p></div></footer>`;
}
function shell({title, description, route, image, body, schema, active}) {
  const canonical = `${base}${route}`;
  const social = `${base}${image || "/assets/og-image-v2.png"}`;
  const [ogWidth,ogHeight] = imageDimensions[(image || "/assets/og-image-v2.png").replace(/^\//,"")] || [1200,630];
  return `<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="referrer" content="strict-origin-when-cross-origin"><title>${html(title)} | Samfa12</title><meta name="description" content="${html(description)}"><meta name="theme-color" content="#050714"><link rel="canonical" href="${html(canonical)}"><link rel="icon" type="image/png" href="/assets/favicon.png"><meta property="og:type" content="website"><meta property="og:title" content="${html(title)} | Samfa12"><meta property="og:description" content="${html(description)}"><meta property="og:url" content="${html(canonical)}"><meta property="og:image" content="${html(social)}"><meta property="og:image:width" content="${ogWidth}"><meta property="og:image:height" content="${ogHeight}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${html(title)} | Samfa12"><meta name="twitter:description" content="${html(description)}"><meta name="twitter:image" content="${html(social)}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@500;700&family=Inter:wght@400;600;700;800;900&family=Space+Grotesk:wght@500;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css?v=${assetVersion}"><script type="application/ld+json">${jsonLd(schema)}</script></head><body data-page="product">${header(active)}<main id="main">${body}</main>${footer()}<script src="/script.js?v=${assetVersion}" defer></script></body></html>\n${generatedMarker}\n`;
}
const parentLabels = new Map([["/games/","Games"],["/apps/","Apps"],["/books/","Books"],["/music/","Music"],["/pocket-audio/","Pocket Audio"]]);
function parentLabel(parent) {
  const label = parentLabels.get(parent);
  if (!label) throw Error(`Unknown product parent ${parent}`);
  return label;
}
function breadcrumbs(route, title, parent) {
  return `<nav class="product-breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="${parent}">${html(parentLabel(parent))}</a><span aria-hidden="true">/</span><span aria-current="page">${html(title)}</span></nav>`;
}
function productPage(plan, project, content) {
  const route = plan.path;
  const pageTitle = content.seoTitle || (project.id === "game-dust-on-the-river" ? "Dust on the River game" : project.id === "book-dust-on-the-river" ? "Dust on the River novel" : project.title);
  const parent = route.startsWith("/books/") ? "/books/" : route.startsWith("/music/") ? "/music/" : route.startsWith("/pocket-audio/") ? "/pocket-audio/" : route.startsWith("/tools/") ? "/apps/" : "/games/";
  const intro = content.intro || project.description;
  const description = content.metaDescription || intro;
  const image = `/${project.thumbnail}`;
  const actions = (project.links || []).map((l) => link(l.label, l.url, "project-link"+(l===project.links[0]?" project-link-primary":""))).join(" ");
  const details = (content.details || []).map((item) => `<section class="product-prose"><h2>${html(item.heading)}</h2><p>${html(item.text)}</p></section>`).join("\n");
  const faq = content.faqs?.length ? `<section class="section section-tight"><div class="container product-narrow"><h2>Questions about ${html(project.title)}</h2><div class="product-faqs">${content.faqs.map((f)=>`<details><summary>${html(f.question)}</summary><p>${html(f.answer)}</p></details>`).join("")}</div></div></section>` : "";
  const updates = content.updates?.length ? `<section class="section section-tight"><div class="container product-narrow"><h2>${project.category === "Books" ? "Publication and edition updates" : "Updates"}</h2>${content.updates.map((u)=>`<article class="product-update" id="${html(u.id)}"><p class="eyebrow">${html(u.date)} · ${html(u.dateMeaning)}</p><h3>${html(u.title)}</h3><p>${html(u.summary)}</p></article>`).join("")}</div></section>` : "";
  const related = (content.relatedIds || []).map((id)=>{const other = plansById.get(id); return other && other.path !== route && other.action !== "hold" ? `<li><a href="${html(other.path)}">${html(content.relatedLabels?.[id] || other.title)}</a></li>` : "";}).filter(Boolean);
  related.push(...hubs.filter((hub)=>hub.books.includes(plan.id)).map((hub)=>`<li><a href="${html(hub.route)}">${html(hub.title)} reading order</a></li>`));
  const relatedBlock = related.length ? `<section class="section section-tight"><div class="container product-narrow"><h2>Related projects</h2><ul class="product-related">${related.join("")}</ul></div></section>` : "";
  const evidenceLinks = [...new Set([...(content.details || []).flatMap((d)=>d.sources || []),...(content.faqs || []).flatMap((f)=>f.sources || [])])].filter((s)=>/^https?:/.test(s));
  const sources = evidenceLinks.length ? `<section class="section section-tight"><div class="container product-narrow"><h2>Official sources</h2><ul class="product-related">${evidenceLinks.map((s)=>`<li><a href="${html(safeUrl(s))}" target="_blank" rel="noopener noreferrer">${html(new URL(s).hostname)} · ${html(new URL(s).pathname.split("/").filter(Boolean).pop() || "profile")}</a></li>`).join("")}</ul></div></section>` : "";
  const [imageWidth, imageHeight] = imageDimensions[project.thumbnail] || [640, 540];
  const body = `<section class="page-hero product-hero"><div class="container">${breadcrumbs(route, project.title, parent)}<div class="product-layout"><div><p class="eyebrow">${html(project.type || project.category)} · ${html(project.status)}</p><h1>${html(project.title)}</h1>${content.authorCredit ? `<p class="product-author">By ${html(content.authorCredit)}</p>` : ""}<p class="lead">${html(intro)}</p><div class="product-actions">${actions}</div></div><img class="product-hero-art" src="${html(image)}" alt="${html(project.thumbnailAlt || `${project.title} artwork`)}" width="${imageWidth}" height="${imageHeight}"></div></div></section><section class="section section-tight"><div class="container product-narrow">${details}</div></section>${faq}${updates}${relatedBlock}${sources}`;
  const type = project.category === "Books" ? "Book" : project.category === "Music" ? "MusicAlbum" : project.category === "Apps & Tools" || project.category === "Assets" ? "SoftwareApplication" : ["game-td-pack","game-lofi-and-chill-pack"].includes(project.id) ? "CreativeWork" : "VideoGame";
  const graph = [{"@type":"Organization","@id":`${base}/#organization`,name:"Samfa12",url:`${base}/`},{"@type":"WebSite","@id":`${base}/#website`,url:`${base}/`,name:"Samfa12",publisher:{"@id":`${base}/#organization`}},{"@type":"WebPage","@id":`${base}${route}#webpage`,url:`${base}${route}`,name:`${pageTitle} | Samfa12`,description,mainEntity:{"@id":`${base}${route}#product`},isPartOf:{"@id":`${base}/#website`}},{"@type":type,"@id":`${base}${route}#product`,name:project.title,description: intro,url:`${base}${route}`,image:`${base}${image}`,publisher:{"@id":`${base}/#organization`}},{"@type":"BreadcrumbList","@id":`${base}${route}#breadcrumbs`,itemListElement:[{ "@type":"ListItem",position:1,name:"Home",item:`${base}/`},{"@type":"ListItem",position:2,name:parentLabel(parent),item:`${base}${parent}`},{"@type":"ListItem",position:3,name:project.title,item:`${base}${route}`}]}];
  if (type === "Book") delete graph[3].publisher;
  if (type === "MusicAlbum") graph[3].byArtist = {"@id":`${base}/#organization`};
  return shell({title:pageTitle,description,route,image,body,schema:{"@context":"https://schema.org","@graph":graph},active:parent === "/books/" ? "Books" : parent === "/music/" ? "Music" : parent === "/pocket-audio/" ? "Pocket Audio" : parent === "/apps/" ? "Apps" : "Games"});
}

function validate() {
  if (data.length !== manifest.products.length + manifest.directories.length) throw Error("Every catalogue record needs a disposition");
  const ids = new Set(); const routes = new Set();
  for (const project of data) {
    if (!project.id || ids.has(project.id)) throw Error(`Missing/duplicate ID: ${project.id}`);
    ids.add(project.id);
    for (const item of project.links || []) safeUrl(item.url);
    if (project.detailUrl) safeUrl(project.detailUrl);
  }
  for (const plan of manifest.products) {
    if (!productsById.has(plan.id) || plansById.get(plan.id) !== plan) throw Error(`Unknown product ${plan.id}`);
    const relative = safeRoute(plan.path);
    if (routes.has(relative.toLowerCase())) throw Error(`Duplicate route ${plan.path}`);
    routes.add(relative.toLowerCase());
    if (plan.action === "hold") {
      if (!plan.holdReason || productsById.get(plan.id).detailUrl) throw Error(`${plan.id} needs a reason and no detailUrl while held`);
      continue;
    }
    if (productsById.get(plan.id).detailUrl !== plan.path) throw Error(`${plan.id} detailUrl mismatch`);
    if (!Array.isArray(plan.officialSources) || !plan.officialSources.length) throw Error(`${plan.id} needs official sources`);
    const reviewedSources = new Set((sourceReview.products[plan.id]?.sources || []).map((source)=>source.url));
    for (const source of plan.officialSources) {
      if (!/^https:\/\//.test(safeUrl(source)) || !reviewedSources.has(source)) throw Error(`${plan.id} needs a reviewed HTTPS official source: ${source}`);
    }
    if (!copy[plan.id]) throw Error(`${plan.id} is missing editorial copy`);
    const item = copy[plan.id];
    if (!item.intro || !Array.isArray(item.details) || !item.details.length) throw Error(`${plan.id} needs a substantive introduction and detail`);
    for (const id of item.relatedIds || []) if (id === plan.id || !plansById.has(id) || plansById.get(id).action === "hold") throw Error(`${plan.id} has invalid related product ${id}`);
    for (const [id,label] of Object.entries(item.relatedLabels || {})) if (!(item.relatedIds || []).includes(id) || typeof label !== "string" || !label.trim()) throw Error(`${plan.id} has an invalid related label for ${id}`);
    for (const claim of [...item.details,...(item.faqs || [])]) {
      if (!Array.isArray(claim.sources) || !claim.sources.length) throw Error(`${plan.id} claim lacks sources`);
      claim.sources.forEach(safeUrl);
    }
    for (const update of item.updates || []) {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(update.date) || !update.dateMeaning || !update.id || !update.kind || !update.sources?.length) throw Error(`${plan.id} has invalid update`);
      update.sources.forEach(safeUrl);
    }
  }
}

validate();
validateUpdateDates(siteRoutes,manifest,copy);
for (const [relative, page] of [["index.html","home"],["games/index.html","Games"],["books/index.html","Books"],["apps/index.html","apps"],["pocket-audio/index.html","pocket-audio"],["music/index.html","Music"],["links/index.html","links"]]) {
  const cards = selected(page).map((p,i)=>card(p,i,page === "home")).join("\n");
  replaceManaged(relative, "<!-- content:grid:start -->", "<!-- content:grid:end -->", cards);
}
const sectionMeta = [
  ["index.html","home","/","Samfa12","Games, books, music and Pocket Audio from Samfa12."],
  ["games/index.html","Games","/games/","Games","Samfa12 games and browser prototypes."],
  ["books/index.html","Books","/books/","Books","Samfa12 novels, novellas and reading order."],
  ["apps/index.html","apps","/apps/","Apps","Samfa12 apps and creative tools."],
  ["pocket-audio/index.html","pocket-audio","/pocket-audio/","Pocket Audio","Compose, perform and transfer Pocket Audio songs."],
  ["music/index.html","Music","/music/","Music","Samfa12 albums and listening destinations."],
  ["links/index.html","links","/links/","Links","Official Samfa12 profiles and storefronts."],
];
for (const [relative,page,route,title,description] of sectionMeta) {
  const items = selected(page).map((p,index)=>({"@type":"ListItem",position:index+1,name:p.title,url: p.detailUrl ? `${base}${p.detailUrl}` : /^https?:/.test(p.links?.[0]?.url || "") ? p.links[0].url : `${base}${p.links?.[0]?.url || route}`}));
  const org = {"@type":"Organization","@id":`${base}/#organization`,name:"Samfa12",url:`${base}/`,logo:`${base}/assets/favicon.png`};
  if (route === "/") org.sameAs = ["https://github.com/Samfa12-tech","https://x.com/Samfa12","https://www.facebook.com/profile.php?id=61577421161868","https://www.reddit.com/user/Samfa12/","https://samfa12.itch.io/","https://play.google.com/store/apps/dev?id=7761853381809168545","https://www.amazon.com.au/stores/Samfa-12/author/B0GTPM5KF2?ref=ap_rdr&shoppingPortalEnabled=true","https://open.spotify.com/artist/6ZDb5x10yqra2d6lBCpnkS","https://www.youtube.com/@samsmall12"];
  const graph = [org,{"@type":"WebSite","@id":`${base}/#website`,url:`${base}/`,name:"Samfa12",publisher:{"@id":`${base}/#organization`}},{"@type":route === "/" ? "WebPage" : "CollectionPage","@id":`${base}${route}#webpage`,url:`${base}${route}`,name:title,description,isPartOf:{"@id":`${base}/#website`},mainEntity:{"@id":`${base}${route}#list`}},{"@type":"ItemList","@id":`${base}${route}#list`,itemListElement:items}];
  const start = "<!-- content:schema:start -->", end = "<!-- content:schema:end -->";
  const source = outputs.get(relative);
  const a = source.indexOf(start), b = source.indexOf(end);
  if (a < 0 || b < a) throw Error(`Missing schema markers in ${relative}`);
  outputs.set(relative,source.slice(0,a+start.length)+`\n<script type="application/ld+json">${jsonLd({"@context":"https://schema.org","@graph":graph})}</script>\n`+source.slice(b));
}
for (const [route,name] of [["/stats/","Marketplace statistics"],["/join/","Join Samfa12"],["/privacy/","Privacy"]]) {
  const graph = [organizationNode(),websiteNode(),pageNode(route,name)];
  replaceManaged(`${route.slice(1)}index.html`,"<!-- content:schema:start -->","<!-- content:schema:end -->",`<script type="application/ld+json">${jsonLd({"@context":"https://schema.org","@graph":graph})}</script>`);
}
{
  const relative = "links/index.html";
  const source = outputs.get(relative);
  const start = "<!-- content:links:start -->", end = "<!-- content:links:end -->";
  const a = source.indexOf(start), b = source.indexOf(end);
  if (a < 0 || b < a) throw Error("Missing link-group markers");
  const groups = linkGroups.map((group)=>`<section class="link-group"><h2>${html(group.title)}</h2><div class="link-group-list">${group.links.map(([label,url])=>link(label,url,"link-group-link")).join("")}</div></section>`).join("\n");
  outputs.set(relative,source.slice(0,a+start.length)+"\n"+groups+"\n"+source.slice(b));
}
for (const plan of manifest.products.filter((p)=>p.action.startsWith("enhance"))) {
  const relative = safeRoute(plan.path);
  const project = productsById.get(plan.id);
  const content = copy[plan.id];
  let output = fs.readFileSync(path.join(root,relative),"utf8");
  const faq = content.faqs?.length ? `<section class="section section-tight"><div class="container product-narrow"><h2>Questions about ${html(project.title)}</h2><div class="product-faqs">${content.faqs.map((f)=>`<details><summary>${html(f.question)}</summary><p>${html(f.answer)}</p></details>`).join("")}</div></div></section>` : "";
  const updates = content.updates?.length ? `<section class="section section-tight"><div class="container product-narrow"><h2>Release updates</h2>${content.updates.map((u)=>`<article class="product-update" id="${html(u.id)}"><p class="eyebrow">${html(u.date)} · ${html(u.dateMeaning)}</p><h3>${html(u.title)}</h3><p>${html(u.summary)}</p></article>`).join("")}</div></section>` : "";
  const actions = project.links.filter((item)=>item.url!==plan.path).map((item)=>link(item.label,item.url)).join(" ");
  const related = (content.relatedIds || []).map((id)=>plansById.get(id)).filter(Boolean);
  const relatedBlock = related.length ? `<section class="section section-tight"><div class="container product-narrow"><h2>Related projects</h2><ul class="product-related">${related.map((item)=>`<li><a href="${html(item.path)}">${html(content.relatedLabels?.[item.id] || item.title)}</a></li>`).join("")}</ul></div></section>` : "";
  const body = `<section class="section section-tight"><div class="container product-narrow"><h2>Using ${html(project.title)}</h2><p>${html(content.intro)}</p>${content.details.map((d)=>`<div class="product-prose"><h3>${html(d.heading)}</h3><p>${html(d.text)}</p></div>`).join("")}${actions ? `<div class="product-actions">${actions}</div>` : ""}</div></section>${faq}${updates}${relatedBlock}`;
  const parent = project.category === "Games" ? "/games/" : "/apps/";
  const graph = [organizationNode(),websiteNode(),{...pageNode(plan.path,project.title),mainEntity:{"@id":`${base}${plan.path}#product`}},{"@type":project.category === "Games" ? "VideoGame" : "SoftwareApplication","@id":`${base}${plan.path}#product`,name:project.title,description:content.intro,url:`${base}${plan.path}`},{"@type":"BreadcrumbList","@id":`${base}${plan.path}#breadcrumbs`,itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:`${base}/`},{"@type":"ListItem",position:2,name:parentLabel(parent),item:`${base}${parent}`},{"@type":"ListItem",position:3,name:project.title,item:`${base}${plan.path}`}]}];
  for (const [start,end,value] of [["<!-- content:existing:start -->","<!-- content:existing:end -->",body],["<!-- content:schema:start -->","<!-- content:schema:end -->",`<script type="application/ld+json">${jsonLd({"@context":"https://schema.org","@graph":graph})}</script>`]]) {
    const from = output.indexOf(start), to = output.indexOf(end);
    if (from < 0 || to < from) throw Error(`Missing ${start} in ${relative}`);
    output = output.slice(0,from+start.length)+"\n"+value+"\n"+output.slice(to);
  }
  write(relative,output);
}
for (const plan of manifest.products) {
  if (plan.action !== "create") continue;
  write(safeRoute(plan.path), productPage(plan, productsById.get(plan.id), copy[plan.id]));
}
for (const hub of hubs) {
  const route = hub.route;
  const items = hub.books.map((id)=>{
    const plan = plansById.get(id);
    if (!plan || plan.action === "hold") throw Error(`Unpublished hub member ${id}`);
    const project = productsById.get(id);
    return `<li><h2><a href="${html(plan.path)}">${html(project.title)}</a></h2><p>${html(copy[id].intro)}</p>${link("View book page",plan.path)}</li>`;
  });
  const body = `<section class="page-hero"><div class="container hero-inner">${breadcrumbs(route,hub.title,"/books/")}<p class="eyebrow">Reading order</p><h1>${html(hub.title)}</h1><p class="lead">${html(hub.intro)}</p></div></section><section class="section"><div class="container product-narrow"><ol class="product-series-list">${items.join("")}</ol><h2>Official author pages</h2><ul class="product-related">${hub.sources.map((s)=>`<li>${link(new URL(s).pathname.split("/").filter(Boolean).pop(),s)}</li>`).join("")}</ul></div></section>`;
  const entity = hub.type === "BookSeries" ? {"@type":"BookSeries","@id":`${base}${route}#series`,name:hub.title,hasPart:hub.books.map((id)=>({"@type":"Book",url:`${base}${plansById.get(id).path}`}))} : {"@type":"ItemList","@id":`${base}${route}#list`,itemListElement:hub.books.map((id,index)=>({"@type":"ListItem",position:index+1,url:`${base}${plansById.get(id).path}`}))};
  const breadcrumb = {"@type":"BreadcrumbList","@id":`${base}${route}#breadcrumbs`,itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:`${base}/`},{"@type":"ListItem",position:2,name:"Books",item:`${base}/books/`},{"@type":"ListItem",position:3,name:hub.title,item:`${base}${route}`} ]};
  write(safeRoute(route),shell({title:hub.title,description:hub.description,route,body,schema:{"@context":"https://schema.org","@graph":[organizationNode(),websiteNode(),{...pageNode(route,hub.title),mainEntity:{"@id":entity["@id"]}},entity,breadcrumb]},active:"Books"}));
}
const allUpdates = manifest.products.flatMap((plan)=>(copy[plan.id]?.updates || []).map((item)=>({...item,projectId:plan.id,projectTitle:plan.title,projectPath:plan.path}))).sort((a,b)=>b.date.localeCompare(a.date));
const updatesBody = `<section class="page-hero"><div class="container hero-inner"><p class="eyebrow">Release notes and announcements</p><h1>Updates</h1><p class="lead">Verified release notes, store changes and project announcements. Each date describes the event named with it.</p></div></section><section class="section"><div class="container product-narrow">${allUpdates.map((u)=>`<article class="product-update"><p class="eyebrow">${html(u.date)} · ${html(u.dateMeaning)}</p><h2><a href="${html(u.projectPath)}#${html(u.id)}">${html(u.projectTitle)}: ${html(u.title)}</a></h2><p>${html(u.summary)}</p></article>`).join("") || "<p>There are no sourced public updates yet.</p>"}</div></section>`;
write("updates/index.html", shell({title:"Updates",description:"Verified Samfa12 release notes, store updates and project announcements.",route:"/updates/",body:updatesBody,schema:{"@context":"https://schema.org","@graph":[organizationNode(),websiteNode(),pageNode("/updates/","Samfa12 updates","CollectionPage")]},active:""}));
const aboutBody = `<section class="page-hero"><div class="container hero-inner"><p class="eyebrow">Independent creative work</p><h1>About Samfa12</h1><p class="lead">Samfa12 publishes games, books, music and creative tools. This site brings the projects together and links to their official play, reading, listening and download destinations.</p></div></section><section class="section"><div class="container product-narrow"><h2>Explore the work</h2><p>Browse <a href="/games/">games</a>, <a href="/books/">books</a>, <a href="/music/">music</a> and <a href="/pocket-audio/">Pocket Audio tools</a>. Product pages explain what each project offers and point to its direct destination.</p><p>For public profiles and storefronts, visit the <a href="/links/">links directory</a>.</p></div></section>`;
write("about/index.html", shell({title:"About",description:"About Samfa12 and its games, books, music and creative tools.",route:"/about/",body:aboutBody,schema:{"@context":"https://schema.org","@graph":[organizationNode(),websiteNode(),pageNode("/about/","About Samfa12","AboutPage")]},active:""}));
const sitemapRoutes = sitemapEntries(siteRoutes,manifest,hubs);
if (new Set(sitemapRoutes.map(([route])=>route.toLowerCase())).size !== sitemapRoutes.length) throw Error("Duplicate sitemap route");
for (const [route,date] of sitemapRoutes) if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || Number.isNaN(Date.parse(date))) throw Error(`Missing meaningful modification date for ${route}`);
write("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapRoutes.map(([route,date])=>`  <url><loc>${xml(base+route)}</loc><lastmod>${date}</lastmod></url>`).join("\n")}\n</urlset>\n`);

const generatedPages = [...outputs].filter(([relative,source])=>relative.endsWith("/index.html") && source.includes(generatedMarker)).map(([relative])=>relative).sort();
const generatedManifestPath = path.join(root,"content/generated-output-manifest.json");
const previousGenerated = fs.existsSync(generatedManifestPath) ? JSON.parse(fs.readFileSync(generatedManifestPath,"utf8")) : {pages:[]};
if (!Array.isArray(previousGenerated.pages)) throw Error("Invalid previous generated-page manifest");
for (const relative of previousGenerated.pages) {
  if (!/^[a-z0-9-]+(?:\/[a-z0-9-]+)*\/index\.html$/.test(relative) || ["apps/pocket-chordsmith/index.html","apps/pocket-dj/index.html","apps/what-would-win/index.html","games/briarhold/play/index.html"].includes(relative)) throw Error(`Unsafe managed path ${relative}`);
  if (generatedPages.includes(relative)) continue;
  const absolute = path.join(root,relative);
  if (!fs.existsSync(absolute)) continue;
  if (!fs.readFileSync(absolute,"utf8").includes(generatedMarker)) throw Error(`Refusing to remove unmanaged page ${relative}`);
  if (check) errors.push(`Stale generated page: ${relative}`);
  else fs.unlinkSync(absolute);
}
write("content/generated-output-manifest.json",JSON.stringify({pages:generatedPages},null,2)+"\n");

for (const [relative, expected] of outputs) {
  const absolute = path.join(root, relative);
  if (check) {
    if (!fs.existsSync(absolute) || fs.readFileSync(absolute,"utf8").replace(/\r\n/g,"\n") !== expected) errors.push(`Stale generated output: ${relative}`);
  } else {
    fs.mkdirSync(path.dirname(absolute),{recursive:true});
    fs.writeFileSync(absolute,expected,"utf8");
  }
}
if (errors.length) { console.error(errors.join("\n")); process.exit(1); }
console.log(`${check ? "Checked" : "Built"} ${outputs.size} content outputs, ${manifest.products.length} product dispositions, ${allUpdates.length} updates.`);
